"""empty message

Revision ID: 48f9cea1878f
Revises: 80326a97a197
Create Date: 2018-07-21 01:55:14.281215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48f9cea1878f'
down_revision = '80326a97a197'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pfi', sa.Column('cost', sa.Integer(), nullable=False))
    op.add_column('pfi', sa.Column('hs_code', sa.Integer(), nullable=False))
    op.add_column('pfi', sa.Column('items_detail', sa.Text(), nullable=True))
    op.add_column('pfi', sa.Column('pft_type', sa.String(length=80), nullable=True))
    op.add_column('pfi', sa.Column('quantity', sa.Integer(), nullable=False))
    op.add_column('pfi', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('pfi', sa.Column('url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pfi', 'url')
    op.drop_column('pfi', 'updated_at')
    op.drop_column('pfi', 'quantity')
    op.drop_column('pfi', 'pft_type')
    op.drop_column('pfi', 'items_detail')
    op.drop_column('pfi', 'hs_code')
    op.drop_column('pfi', 'cost')
    # ### end Alembic commands ###
