"""empty message

Revision ID: 914e9055ad37
Revises: 1ce0d9c587d7
Create Date: 2018-07-21 09:00:16.809830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '914e9055ad37'
down_revision = '1ce0d9c587d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pfi', sa.Column('pfi_number', sa.Integer(), nullable=False))
    op.add_column('pfi', sa.Column('supplier_name', sa.String(length=80), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pfi', 'supplier_name')
    op.drop_column('pfi', 'pfi_number')
    # ### end Alembic commands ###
