"""empty message

Revision ID: 979028aa2fca
Revises: eb8396466296
Create Date: 2018-07-21 20:37:37.185124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '979028aa2fca'
down_revision = 'eb8396466296'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requiredpermission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('permission_name', sa.String(length=80), nullable=False),
    sa.Column('gotten', sa.Boolean(), nullable=True),
    sa.Column('shipments_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['shipments_id'], ['shipments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('requiredpermission')
    # ### end Alembic commands ###
