"""empty message

Revision ID: eb8396466296
Revises: fe15c4205329
Create Date: 2018-07-21 14:10:57.116505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb8396466296'
down_revision = 'fe15c4205329'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('formm', sa.Column('formm_number', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('formm', 'formm_number')
    # ### end Alembic commands ###
